# Stage 1: Build the JAR file
FROM openjdk:17-jdk-alpine as builder

# Set the working directory inside the builder container
WORKDIR /app

# Copy the project files into the builder container
COPY . .

# Build the project to create the JAR file
RUN ./mvnw.cmd clean package

# Stage 2: Create the final image
FROM openjdk:17-jdk-alpine

# Set the working directory inside the container
WORKDIR /app

# Copy the JAR file from the builder stage
COPY --from=builder /app/target/database-connector-0.0.1-SNAPSHOT.jar /app/app.jar

# Expose port 8080
EXPOSE 8080

# Command to run your Spring Boot application when the container starts
ENTRYPOINT ["java", "-jar", "/app/app.jar"]